[[redirects]]
  from = "/*"
  to = "/intro"
  status = 200

[[redirects]]
  from = "/*"
  to = "/experience"
  status = 200

[[redirects]]
  from = "/*"
  to = "/projects"
  status = 200

[[redirects]]
  from = "/*"
  to = "/contact"
  status = 200